default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  username: root
  password: root

development:
  <<: *default
  database: kakeibo-app_development

test:
  <<: *default
  database: kakeibo-app_test

production:
  <<: *default
  database: kakeibo-app_production